levels = {
  1:{
    "tiles":[
      [
        [1,1,1,1,2]
      ]
    ],
    "objects":{
      "player":{
        "sprite":"robot-1",
        "pos":[0,0,1]
      }
    }
  },
  2:{
    "tiles":[
      [
        [1,1,1,1,1],
        [1,1,1,1,1],
        [1,1,1,1,1],
        [1,1,1,1,1],
        [1,1,1,1,2]
      ]
    ],
    "objects":{
      "player":{
        "sprite":"robot-2",
        "pos":[0,0,1]
      }
    }
  },
  3:{
    "tiles":[
      [
        [1,0,1,1,1],
        [1,0,1,0,1],
        [1,0,1,0,1],
        [1,0,1,0,1],
        [1,1,1,0,2]
      ]
    ],
    "objects":{
      "player":{
        "sprite":"robot-2",
        "pos":[0,0,1]
      }
    }
  },
  4:{
    "tiles":[
      [
        [1,1,1,1,1,2],
        [1],
        [1],
        [1],
        [1]
      ]
    ],
    "objects":{
      "checkpoint":{
        "sprite":"checkpoint-1",
        "pos":[0,5,0]
      },
      "player":{
        "sprite":"robot-2",
        "pos":[0,0,1]
      }
    }
  },
  5:{
    "tiles":[
      [
        [1,1,1,1],
        [1,0,0,1],
        [1,0,0,1,1,1],
        [0,0,0,0,0,1],
        [0,0,0,2,1,1]
      ]
    ],
    "objects":{
      "checkpoint":{
        "sprite":"checkpoint-1",
        "pos":[0,3,0]
      },
      "player":{
        "sprite":"robot-2",
        "pos":[0,0,1]
      }
    }
  }
}